from config import DATABASE_SCHEMA_FULL_DIR, DATABASE_SCHEMA_MIGRATIONS_DIR

FULL_SCHEMAS = {
    1: DATABASE_SCHEMA_FULL_DIR / "v1.sql",
}

MIGRATIONS = {
    0: DATABASE_SCHEMA_FULL_DIR / "v1.sql",
    1: DATABASE_SCHEMA_MIGRATIONS_DIR / "1_to_2.sql",
}
